name: Daily File Update

on:
  schedule:
    - cron: '0 9 * * *' # Her gün 09:00'da çalışır (UTC saatiyle)
  workflow_dispatch: # Manuel tetikleme için

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || true # Gerekirse bağımlılıkları yükle

      - name: Run Python script
        run: python script.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add outputs/
          git commit -m "Günlük dosya güncellemesi: $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
